- Gemfile.lock
From https://github.com/sharesight/helpsite/pull/38
> Updates nokogiri from an unsafe version.

- source/js/search.js.es6.erb
[ticket](https://vimaly.com/#j8mqm/t/help_site_search_-_pressing_enter_clears_text_in_s.../aSjXzOABn5iKtDY6W)
> Properly disable the enter key on the search.

- source/css/_footer.scss
[ticket](https://vimaly.com/#j8mqm/t/Help_app_icons_too_large_in_small_tablet_view/JLt9jZ6KiImJtYOkN)
> Fix app store icons becoming huge on 6xx-7xx screens.

- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- source/layouts/partials/_analytics_js.html.erb
[ticket](https://vimaly.com/#j8mqm/t/help_Ensure_Intercom_still_functions_as_normal./q6cuTvJPnSs624mYw)
> Fix Intercom and remove Optimizely

- Gemfile.lock
current version had a vulnerability
> update ffi gem to safe version

- mappers/help/page.rb
- source/help-page.html.erb
[ticket](https://vimaly.com/#j8mqm/t/help_site_Update_Contentful_image_paths/7ZSUhMNRZQyd2bTpi)
> Fix asset redirection contentful images

- config.rb
[ticket](https://vimaly.com/#j8mqm/t/help_Cleanup_S3_Redirects_and_Old_Files_like_we_di.../UaSlTteQgFONBwYI6)
See: https://github.com/sharesight/www.sharesight.com/pull/94
> Delete old, unbuilt s3 files when redeploying.

- Gemfile.lock
update rubyzip to safe version
> deal with vulnerability cve-2019-16892

- Gemfile
- Gemfile.lock
see [story](https://vimaly.com/#j8mqm/t/helpsite_update_helpsite_for_bundle_audit_warning./00zYUn5T4KNjEPaIF)
> update nokogiri to bundle audit's recommended version

- Gemfile.lock
See details: https://github.com/advisories/GHSA-jppv-gw3r-w3q8
> update rake to avoid CVE-2020-8130

- .github/workflows/bundle-audit.yml
Will require a major middleman version update to resolve
> Ignore CVE-2020-8184 for now

- source/css/_footer.scss
- source/partials/_footer.html.erb
Basically the same as https://github.com/sharesight/www.sharesight.com/pull/203, just for the helpsite.
> Refactor the Footer Links to Flex

- source/css/_footer.scss
- source/partials/_footer.html.erb
- spec/features/footer_spec.rb
[vimaly](https://vimaly.com/#j8mqm/t/www_Add_Reviews_link_to_footer/Xc1vCD2gUb4AYNzCY)
> Add reviews link to footer and footers spec

- source/partials/_footer.html.erb
- spec/features/footer_spec.rb
[vimaly](https://vimaly.com/#j8mqm/t/www_help_Add_Affiliates_link_to_website_footers/4RYwI3PBhqUwXlAh9)
Desktop
Mobile
> Add affiliates link to site footer

- source/partials/_footer.html.erb
- spec/features/footer_spec.rb
Vimaly:
https://vimaly.com/#j8mqm/t/www_help_Update_Partners_Footer_Links/cSYtjQaSerR7OyE49
> Add "Partner with Us" to the footer.

- config.rb
See https://github.com/sharesight/www.sharesight.com/pull/239 for more information.
> Limit `all_entries_page_size` to paginate data.

- .github/dependabot.yml
Noticed this wasn't done here…I don't particularly like having you review, but also hate hard-coding someone's name in here…happy to change it though (or have no reviewers).
> Add Github Actions to dependabot.

- source/partials/_footer.html.erb
Coming from [this story](https://vimaly.com/#j8mqm/t/www_Make_some_readability_and_UX_changes./vWGqOeaGqGvG23boz), but it's really a dead-simple change that I'll do without QA.  Just getting a review for the sake of it!
> Add a label to the region selector for accessibility.

- source/css/_components.accordion.scss
- source/css/_site.scss
This is the same feature as sharesight/www.sharesight.com#279
> Created basic styles for accordions and fixed blog page layout so that opening an accordion details doesn't break the layout.
> 
> [See the story](https://vimaly.com/#j8mqm/t/www_seo_1.5._Get_a_styled_accordion_block_working_.../9JfojOLll8WSrG48n)
> Added styles for accordion - same as #279 in www site

- config/environments/development.rb
- config/environments/staging.rb
- source/partials/_footer.html.erb
- spec/features/footer_spec.rb
Added community forum link to footer and updated staging URL.
Related to https://github.com/sharesight/www.sharesight.com/pull/289
[See the story](https://vimaly.com/#j8mqm/t/Marketing_site_link_to_forum/OJrFDOSIwsVsucAW4)
> Community forum links and content

- .github/dependabot.yml
This is very outdated, Iain is no longer with us as of 4+ months.
This wasn't spamming him, failed without incident: https://github.com/sharesight/www.sharesight.com/pull/355#issuecomment-1033853392
> Remove irwalker as a reviewer.

- source/partials/_footer.html.erb
[Asana ticket can be found here](https://app.asana.com/0/1202529446124670/1203511975029095)
> Removing google and apple icons from footer

- source/layouts/partials/_head.html.erb
https://blog.qualys.com/vulnerabilities-threat-research/2024/06/28/polyfill-io-supply-chain-attack
> Removing Polyfill due to Supply Chain attack
