sharesight/help.sharesight.com

source/layouts/article_layout.html.erb
source/layouts/layout.html.erb

Twitter does not go against the not-so-well-defined spec and does not error or work with relative urls.  Follow up to #7.

Make og:image absolute urls for Twitter to behave.

---

test/build/sanity_check_test.rb

We updated this report and made it available in all locales.  Even if that's not valid, it may be in the future.

Remove tests for reports to not exist in specific locales.

---

Gemfile.lock

See: https://github.com/sparklemotion/nokogiri/pull/1746

Upgrade Nokogiri due to CVE-2018-8048.

---

Gemfile.lock

[ticket](https://vimaly.com/#j8mqm/t/CVE-2018-14404_Update_nokogiri_gem/czhN1dLCtIJxprFzE)

Update Nokoogiri to 1.8.5 for CVE-2018-14404

---

Gemfile.lock

CVE Issue:
https://github.com/sparklemotion/nokogiri/issues/1892

Bump Nokogiri to 1.10.3 for CVE-2019-11068.

---

Gemfile.lock

Could not create automated via [Github](https://github.com/sharesight/help.sharesight.com/network/alert/Gemfile.lock/haml), manually bumped instead.
[CVE Details on NIST](https://nvd.nist.gov/vuln/detail/CVE-2017-1002201)

Bump `haml` for CVE-2017-1002201.

---

spec/models/help_pages_spec.rb

Has `model[:title]` not `model[:name]`.
Makes tests a bit more explicit in their error message.

Fix Contentful test; was not being ran in Travis.

---

spec/models/help_categories_spec.rb
spec/models/help_pages_spec.rb

Removes the help_categories test for this as it does not have localized fields.
CI only and actually can't test this as we skip for non-Production builds.. 🤷‍♂ 
Coming from issue with Helpsite builds which Jess pointed out.

Update the pages' locale test to log the page id.

---

.github/workflows/bundle-audit.yml

neither affects our middleman use here, and both require a major middleman version update

ignore CVE-2020-8161 and CVE-2020-8165. 

---

.github/workflows/bundle-audit.yml

Requires a major middleman version update. If we used build servers
would need to update.
[vulnerability](https://github.com/advisories/GHSA-mqm2-cgpr-p4m6)

Ignore kramdown vulnerability for now

---

.github/workflows/bundle-audit.yml
.github/workflows/main.yml
Gemfile
Gemfile.lock

Just re-implementing these two PRs as this suffers the same fate:
- www.sharesight.com#220
- www.sharesight.com#219

Fix bundler to `v1.x` and fix `bundler-audit` gem naming.

---

Gemfile
Gemfile.lock

This package currently has open Security Vulnerability around it and is updated in #76.  Ideally, this supersedes as it may be the better course of action.
This appears to be unused.  We do not use it in https://github.com/sharesight/www.sharesight.com and it appears to not be called in our codebase.

Remove unused gem, `redcarpet`.

---

source/css/_footer.scss
source/partials/_footer.html.erb
spec/features/footer_spec.rb

Taking from https://github.com/sharesight/www.sharesight.com/pull/236
We were missing several links, this just brings this 1:1 with the helpsite.
**TODO:**

Update the Helpsite Footer: adds multiple links and Sharesight Pro.

---

.github/workflows/bundle-audit.yml
.github/workflows/main.yml

I noticed a failure on `slatify@v1.8.0` that I couldn't explain (https://github.com/sharesight/help.sharesight.com/runs/2077917171?check_suite_focus=true) and I noticed our versions were mis-matched (master vs. 1.8).  Figured I should make all versions consistent.
In another PR, I've set Dependabot to auto-update these Github Actions.

Specify [latest] versions for `checkout` and `slatify` actions.

---

helpers/middleman/collection.rb
spec/features/help_pages_page_spec.rb
spec/features/index_page_spec.rb
spec/helpers/middleman/collection_spec.rb
spec/support/helpers/collection.rb

Vimaly Story: https://vimaly.com/#j8mqm/t/help_Hide_the_Miscellaneous_category_from_IA./iVrDivkZXuXexNLWy
tl;dr: Customer Support have restructured the help site content and put duplicates or things that shouldn't live in the IA into a `Miscellaneous` category.  They want this `Miscellaneous` category hidden.
---
The complexity here was just finding the places it might fail tests, I think I described that well.

Filter the `Miscellaneous` category from being visible.

---

Gemfile.lock

See sharesight/investapp#10207 for full investigation in our primary product.
Tracked on [Vimaly Ticket](https://vimaly.com/#j8mqm/t/Nokogiri_CVE/31Y5H8h7rxMm3HFF7)
CVEs:
- CVE-2022-24839
- CVE-2022-24836
- CVE-2018-25032
- CVE-2022-23437
Changelog: https://nokogiri.org/CHANGELOG.html#1134-2022-04-11

Bump to latest Nokogiri for CVE

---

Gemfile.lock

In order to handle security issues:
- CVE-2022-29181
- GHSA-xh29-r2w5-wx8m
- GHSA-cgx6-hpwq-fhv5
According to their changelog those patches are only internal changes without any breaking changes.
---
⚠️ Unfortunately I cannot run `bundle` in this repo [on an M1] as the test suite installs an `ffi` gem version which does not natively compile.  I believe this is the correct bump, however; just done manually copied from https://github.com/sharesight/www.sharesight.com/pull/377.

Update the `nokogiri` gem from 1.13.4 to 1.13.6

---

.bundler-audit.yml

Ignore these `rack` CVEs because we cannot upgrade Middleman:
- CVE-2022-30123
- GHSA-wq4h-7r42-5hrr
- CVE-2022-30122
- GHSA-hxqx-xwvh-44m2
We did this in [Investapp](https://github.com/sharesight/investapp/pull/10481), but this is a local, development dependency and we are too far off the version to bump.

Ignore `rack` CVEs

---

.github/workflows/main.yml
README.md
config/environments/production.rb
config/environments/staging.rb
source/layouts/partials/_analytics_js.html.erb

We haven't had any Bugsnags in the past 60 days so it's either that this isn't working correctly or it's not valid.  Given we don't actively maintain this and we're cleaning up Bugsnag, we should clean this up.
The Github Action which sent releases appeared to no longer be working as the last one was >2 years old.  The
`secrets.BUGSNAG_API_KEY` and the Bugsnag project itself should be deleted.

Remove Bugsnag

---

Gemfile
Gemfile.lock

Bump to handle [CVE-2022-32209](https://github.com/advisories/GHSA-pg8v-g4xq-hww9). (Same update as in [investapp](https://github.com/sharesight/investapp/pull/10622) and [www.sharesight.com](https://github.com/sharesight/www.sharesight.com/pull/384))
No story.

Bump rails-html-sanitizer 1.0.4 -> 1.4.3

---

helpers/middleman/collection.rb
source/contents.json.erb
source/js/search.js.es6.erb
spec/helpers/middleman/collection_spec.rb

For context:
- 
- This is part of the work towards the help site migration.
- So that when users search for articles in the help site, we can easily redirect the users to the new page the content now lives on - in static-www
✅ In this PR: 
-
- Added an extra `url` field to the objects in `contents.json` which will contain full length paths e.g. 'https://help.sharesight.com/au/drp' or 'https://www.sharesight.com/supported-stock-exchanges-managed-funds-mutual-funds/'
- Added some functions that will return the full help site link or full static-www link depending on if `static_url_slug` is present
- Updating the search functions to return full urls - either static site urls or help site urls
**In addition to this PR, a contentful change will be required:** 
- adding a field static_url_slug …

Adding url field to `contents.json.erb` that returns static-www or help link

---

source/partials/_footer.html.erb
spec/features/footer_spec.rb

- Update `Sharesight Pro` label to `Sharesight Business` and `Pro Terms of Use` to `Business Terms of Use` in the footer
- [Asana](https://app.asana.com/0/1202529446124670/1209779457750930)

Updating sharesight pro labelling to sharesight business in footer

---

config/contentful.rb
config/initializers/uri.rb

for `URI.un…escape` snd get around this warning with Ruby 2.7:
```
lib/middleman-core/util.rb:71: warning: URI.unescape is obsolete
```

Introduce monkey-patch to circumvent deprecation warnings

---

.github/workflows/main.yml
config/environments/production.rb
config/environments/staging.rb
config/initializers/uri.rb

Recently due to SOC2 compliance, some IAM Users were detected with long lived credentials and deleted. One of the users was help_deploy, which was used to deploy the help site. This PR introduces a safer STS token based authentication method which uses a temporary auth token to push new files to S3.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210553776358858

fix: Permissions for Build and Push to S3

---

config.rb
config/environments/production.rb
config/environments/staging.rb

Getting a 403 forbidden error on s3_sync. This adds the session token that is missing from the authorization.

fix: Add Session Token for S3 Sync command
